version: '3'

volumes:
  postgres_data:

networks:
  fpm_net:
  db_net:
  nginx_net:
    external: true

services:
  php-fpm:
    build: phpdocker/php-fpm
    container_name: studentiunimibot_php-fpm
    working_dir: /usr/src/app/
    env_file: .env
    environment:
      - BOT_TOKEN
    volumes:
      - ./src:/usr/src/app/
      - ./vendor:/usr/src/vendor
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      - fpm_net
      - db_net
    restart: always

  unihome-nginx:
    image: nginx:alpine
    container_name: studentiunimibot_nginx
    working_dir: /usr/src/app/
    volumes:
      - ./src:/usr/src/app/
      - ./phpdocker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    networks:
      - fpm_net
      - nginx_net
    restart: always

  postgres:
    image: postgres
    env_file: .env
    container_name: studentiunimibot_postgres
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_net
